# Generated by Django 2.2.13 on 2020-06-18 06:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/icons'),
        ),
    ]
