# Generated by Django 2.2.13 on 2020-06-22 02:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200618_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='image/icons/kyokusyou_symbol_bo9rwy.jpg', null=True, upload_to='image/icons'),
        ),
    ]
