# Generated by Django 2.2.13 on 2020-06-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='プロフィール'),
        ),
    ]
